-- seeds/02_customers.sql
-- users customers
-- INSERT INTO customers (id, name, email, country, street, city, province, zipcode, company, taxnumber) VALUES (1,'Tenshin', 'tenshin@gmail.com','Canada', '56 ST NW', 'Calgary', 'Alberta','T3N 0P3', 'Intuit', '063-8765');